### ISSUE TITLE
Manifest validation fails 

### ISSUE THREAD

**Issue by FynnBe** [deepimagej/models#23]
Currently the manifest validation fails:
```
{'format_version': ['Must be one of: 0.1.0, 0.2.0.'],
 'notebook': {0: {'authors': {0: {'_schema': ['Invalid input type.']},
                              1: {'_schema': ['Invalid input type.']}},
                  'documentation': ['Invalid suffix '
                                    '(https:/github.com/miura/NEUBIAS_AnalystSchool2020/tree/master/Ignacio): '
                                    'tuple index out of range',
                                    'Invalid as_posix '
                                    '(https:/github.com/miura/NEUBIAS_AnalystSchool2020/tree/master/Ignacio): '
                                    'expected local, relative file path.']},
              1: {'authors': {0: {'_schema': ['Invalid input type.']},
                              1: {'_schema': ['Invalid input type.']},
                              2: {'_schema': ['Invalid input type.']},
                              3: {'_schema': ['Invalid input type.']},
                              4: {'_schema': ['Invalid input type.']}},
                  'documentation': ['Invalid suffix '
                                    '(https:/cbia.fi.muni.cz/research/segmentation/fru-net.html): '
                                    'tuple index out of range',
                                    'Invalid as_posix '
                                    '(https:/cbia.fi.muni.cz/research/segmentation/fru-net.html): '
                                    'expected local, relative file path.']}}}

```

The reasons and possible improvements to the validator are discussed here: https://github.com/bioimage-io/spec-bioimage-io/issues/107
Depending on further development of the validator no changes might be required here.

cc @esgomezm @constantinpape

**Comment by esgomezm** [comment]
Hi @FynnBe,

Thank you for reaching this. I guess this error is due to the new version of the spec in which authors and documentation have changed. I’ll try to update some and see how this information is sown in the current version of deepImageJ. If it doesn’t look weird, I’ll update all the models. If not, is it possible to keep them with the version 0.3.1?

Also I’m confused for the `format_version`. I thought it was 0.3.0, 0.3.1 or 0.3.2, but it is suggesting 0.1.0 or 0.2.0

**Comment by constantinpape** [comment]
>  I’ll try to update some and see how this information is sown in the current version of deepImageJ. If it doesn’t look weird, I’ll update all the models.

This is actually an issue in the validator, see https://github.com/bioimage-io/spec-bioimage-io/issues/114. We will fix this very soon and then everything should work. We will let you know when this is done so you can rerun CI and see if this fixes the issue.
