### ISSUE TITLE
Updating bioimageio workflow

### ISSUE THREAD

**Issue by FynnBe** [deepimagej/models#37]
@oeway is this (generation of a manifest.json) still needed?
https://github.com/deepimagej/models/blob/49afaec2596d08dea3462cfe1ed02974ec0e68fa/.github/workflows/compile-manifest.yml#L24-L41

**Comment by FynnBe** [comment]
proposed workflow update: https://github.com/deepimagej/models/pull/38

**Comment by esgomezm** [comment]
Hei

> We don't need that anymore, but not sure if deepimagej uses any of the generated file on gh-pages. @esgomezm may clarify this?

We're not using that one. Instead, we create the same file in our repository so you can remove it if you want.

**Comment by FynnBe** [comment]
ok, as the workflow is currently failing (last run: https://github.com/deepimagej/models/runs/4854793126?check_suite_focus=true), could you fix it? Feel free to move https://github.com/bioimage-io/bioimage-io-models/blob/main/utils/compile_model_manifest.py over here if you do need it as this is not used anywhere else and the whole https://github.com/bioimage-io/bioimage-io-models repository is deprecated... 

If this is not urgent we could also just add another workflow (see https://github.com/deepimagej/models/pull/38) just to get the validation of the collection RDF going again (It currently fails, I would like to propose some changes so it will pass again...)

**Comment by FynnBe** [comment]
I will leave the compile-manifest.yml untouched in #38 then...
