### ISSUE TITLE
Replace n/a to null

### ISSUE THREAD

**Issue by oeway** [deepimagej/models#4]
Hi, the covers are not rendered correctly on bioimageio: https://bioimage.io/#/?partner=deepimagej&tags=deepimagej&type=model

Please replace all the n/a into `null` in model yaml, (n/a will be treated as a string, for covers, bioimageio will treat it as an url).

**Comment by esgomezm** [comment]
Ok, I change all n/a into `null`, thanks!

The only model that was ready for the bioimage.io is the FRUNet, that's why there are many missing details for the other two 😄

**Comment by oeway** [comment]
I see, thanks.
